import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import LocationProvider from "@/provider/LocationsProvider";
import { IResponseAPI } from "@/types/requestsTypes";
import { MapProvider } from "@/provider/MapProvider";
import { getRandomPos } from "@/utils/utils";
import { getAllPositions } from "@/repo/serverActionsRepo";
import PageTransitionEffect from "@/components/pageTransition/pageTransition";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let allData = await getAllPositions();
  return (
    <html lang="en">
      <body className={inter.className}>
        <PageTransitionEffect>
          <LocationProvider locationsData={allData}>
            <MapProvider>{children}</MapProvider>
          </LocationProvider>
        </PageTransitionEffect>
      </body>
    </html>
  );
}
